apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-helm-common-chart
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/ukatru/argocd-examples.git'
        revision: HEAD
        directories:
          # here it will read the paths under configs and the subpaths under the config paths
          - path: git-sync-examples/mgmt/*
  template:
    metadata:
      # you can use the path strings with / delimiter as variables
      name: "{{path.basename}}"
    spec:
      project: default
      source:
        path: HelmCharts/namespace
        repoURL: 'https://github.com/ukatru/argocd-examples.git'
        helm:
          valueFiles:
            - "{{path[2]}}/{{path.basename}}/values.yaml"
      syncPolicy:
        automated:
          prune: true
      destination:
        # specify different destinations
        namespace: 'default'
        server: https://kubernetes.default.svc