apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-git
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    # matrix 'parent' generator
    - matrix:
        generators:
          # git generator, 'child' #1
          - git:
              repoURL: 'https://github.com/ukatru/argocd-examples.git'
              revision: HEAD
              directories:
                - path: git-sync-examples/ClusterConfigs/ClusterAddons/namespace/*/*
          # cluster generator, 'child' #2
          - clusters:
              selector:
                matchLabels:
                  eks-cluster-name: default
  template:
    metadata:
      # you can use the path strings with / delimiter as variables
      name: "{{path[4]}}-{{path.basename}}"
    spec:
      project: management
      source:
        path: HelmCharts/namespace
        repoURL: 'https://github.com/ukatru/argocd-examples.git'
        helm:
          valueFiles:
            - "$values/git-sync-examples/ClusterConfigs/ClusterAddons/namespace/{{path[4]}}/{{path.basename}}/values.yaml"
        repoURL: 'https://github.com/ukatru/argocd-examples.git'
        ref: values
      syncPolicy:
        automated:
          prune: true
      destination:
        # specify different destinations
        server: '{{.server}}'