apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-helm-common-chart
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/ukatru/argocd-examples.git'
        revision: HEAD
        directories:
          # here it will read the paths under configs and the subpaths under the config paths
          - path: git-sync-examples/ClusterConfigs/ClusterAddons/namespace/*/*
  template:
    metadata:
      # you can use the path strings with / delimiter as variables
      name: "{{path[4]}}-{{path.basename}}"
    spec:
      project: management
      source:
        path: HelmCharts/namespace
        repoURL: 'https://github.com/ukatru/argocd-examples.git'
        helm:
          valueFiles:
            - "$values/git-sync-examples/ClusterConfigs/ClusterAddons/namespace/{{path[2]}}/{{path.basename}}/values.yaml"
        repoURL: 'https://github.com/ukatru/argocd-examples.git'
        ref: values
      syncPolicy:
        automated:
          prune: true
      destination:
        # specify different destinations
        server: https://kubernetes.default.svc