apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-helm-common-chart
  namespace: argocd
spec:
  generators:
    # matrix 'parent' generator
    - matrix:
        generators:
          # git generator, 'child' #1
          - git:
              repoURL: 'https://github.com/ukatru/argocd-examples.git'
              revision: HEAD
              directories:
                - path: git-sync-examples/ClusterConfigs/ClusterAddons/namespace/*/*
          # cluster generator, 'child' #2
          - list:
              elements:
              - cluster: mgmt
                url: https://kubernetes.default.svc
  template:
    metadata:
      # you can use the path strings with / delimiter as variables
      name: "{{ cluster }}-{{path.basename}}"
    spec:
      project: management
      source:
        path: HelmCharts/namespace
        repoURL: 'https://github.com/ukatru/argocd-examples.git'
        helm:
          valueFiles:
            - "$values/git-sync-examples/ClusterConfigs/ClusterAddons/namespace/{{path[3]}}/{{path.basename}}/values.yaml"
        repoURL: 'https://github.com/ukatru/argocd-examples.git'
        ref: values
      syncPolicy:
        automated:
          prune: true
      destination:
        # specify different destinations
        namespace: default
        server: '{{ url }}'